name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente
        run: echo "Ambiente pronto!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar testes (exemplo)
        run: echo "Testes executados com sucesso!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Simulação de Deploy
        run: echo "Deploy concluído!"
